import Foundation
import AppKit

public final class ClipboardMonitor {
    private let pasteboard: PasteboardReader
    private let frontmostBundleID: () -> String?
    private let blacklistedBundleIDs: () -> Set<String>
    private let onCapture: (CapturedItem) -> Void
    private var lastChangeCount: Int
    private var timer: Timer?

    public init(pasteboard: PasteboardReader,
                frontmostBundleID: @escaping () -> String?,
                blacklistedBundleIDs: @escaping () -> Set<String>,
                onCapture: @escaping (CapturedItem) -> Void) {
        self.pasteboard = pasteboard
        self.frontmostBundleID = frontmostBundleID
        self.blacklistedBundleIDs = blacklistedBundleIDs
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.4) {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        let types = pasteboard.types()
        let typeNames = Set(types.map(\.rawValue))
        let concealed: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        if !typeNames.isDisjoint(with: concealed) { return }

        let bundle = frontmostBundleID()
        if let b = bundle, blacklistedBundleIDs().contains(b) { return }

        // Order: file > image > text. A file in Finder also brings .string for the path; image
        // overrides text because screenshots can include a stub string.
        if types.contains(.fileURL),
           let path = pasteboard.string(forType: .fileURL) {
            onCapture(CapturedItem(kind: .file, text: path, sourceBundleID: bundle))
            return
        }
        if types.contains(.png),
           let png = pasteboard.data(forType: .png) {
            onCapture(CapturedItem(kind: .image, imageData: png, sourceBundleID: bundle))
            return
        }
        if types.contains(.tiff),
           let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            onCapture(CapturedItem(kind: .image, imageData: png, sourceBundleID: bundle))
            return
        }
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            onCapture(CapturedItem(kind: .text, text: text, sourceBundleID: bundle))
            return
        }
    }
}
