import Foundation
import AppKit
import UniformTypeIdentifiers

public final class ClipboardMonitor {
    private let pasteboard: PasteboardReader
    private let frontmostBundleID: () -> String?
    private let blacklistedBundleIDs: () -> Set<String>
    private let onCapture: (CapturedItem) -> Void
    private var lastChangeCount: Int
    private var timer: Timer?

    public init(pasteboard: PasteboardReader,
                frontmostBundleID: @escaping () -> String?,
                blacklistedBundleIDs: @escaping () -> Set<String>,
                onCapture: @escaping (CapturedItem) -> Void) {
        self.pasteboard = pasteboard
        self.frontmostBundleID = frontmostBundleID
        self.blacklistedBundleIDs = blacklistedBundleIDs
        self.onCapture = onCapture
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.4) {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        let types = pasteboard.types()
        let typeNames = Set(types.map(\.rawValue))
        let concealed: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        if !typeNames.isDisjoint(with: concealed) { return }

        let bundle = frontmostBundleID()
        if let b = bundle, blacklistedBundleIDs().contains(b) { return }

        // Order: file > image > text. A file in Finder also brings .string for the path; image
        // overrides text because screenshots can include a stub string.
        if types.contains(.fileURL),
           let path = pasteboard.string(forType: .fileURL) {
            // If the copied file is an image, ingest the bytes too so it pastes
            // as image data in apps that prefer images (chat, browser, image
            // editors). We keep the source path in CapturedItem.text so the
            // paste path can still expose the file URL for apps that prefer
            // file references (Finder, Slack uploads).
            if let png = ClipboardMonitor.imagePNGData(at: path) {
                onCapture(CapturedItem(kind: .image, text: path,
                                       imageData: png, sourceBundleID: bundle))
            } else {
                onCapture(CapturedItem(kind: .file, text: path, sourceBundleID: bundle))
            }
            return
        }
        if types.contains(.png),
           let png = pasteboard.data(forType: .png) {
            onCapture(CapturedItem(kind: .image, imageData: png, sourceBundleID: bundle))
            return
        }
        if types.contains(.tiff),
           let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            onCapture(CapturedItem(kind: .image, imageData: png, sourceBundleID: bundle))
            return
        }
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            onCapture(CapturedItem(kind: .text, text: text, sourceBundleID: bundle))
            return
        }
    }

    /// If `path` points to an image file ≤20 MB, returns its bytes re-encoded
    /// as PNG (the canonical form our blob store + paste path expect).
    private static func imagePNGData(at path: String) -> Data? {
        let url = URL(fileURLWithPath: path)
        let keys: Set<URLResourceKey> = [.contentTypeKey, .fileSizeKey]
        guard let values = try? url.resourceValues(forKeys: keys),
              values.contentType?.conforms(to: .image) == true else {
            return nil
        }
        // Cap to avoid swallowing huge RAW / PSD files into memory.
        if let size = values.fileSize, size > 20_000_000 { return nil }
        guard let img = NSImage(contentsOf: url),
              let tiff = img.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else {
            return nil
        }
        return png
    }
}
