name: pizzaClip
options:
  bundleIdPrefix: com.jekeun
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.4"
    CURRENT_PROJECT_VERSION: "5"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "projectJAM1s"
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "6.0.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
targets:
  pizzaClip:
    type: application
    platform: macOS
    sources:
      - path: pizzaClip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jekeun.pizzaClip
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: pizzaClip/Info.plist
    dependencies:
      - package: GRDB
        product: GRDB
      - package: KeyboardShortcuts
        product: KeyboardShortcuts
  pizzaClipTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: pizzaClipTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.jekeun.pizzaClipTests
    dependencies:
      - target: pizzaClip
      - package: GRDB
        product: GRDB
schemes:
  pizzaClip:
    build:
      targets:
        pizzaClip: all
        pizzaClipTests: [test]
    test:
      targets:
        - pizzaClipTests
