name: pizzaClip
options:
  bundleIdPrefix: com.jekeun
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.3.1"
    CURRENT_PROJECT_VERSION: "14"
    DEVELOPMENT_TEAM: "R684FN2S7J"
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Developer ID Application: jaekeun park (R684FN2S7J)"
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "6.0.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"
targets:
  pizzaClip:
    type: application
    platform: macOS
    sources:
      - path: pizzaClip
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jekeun.pizzaClip
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: pizzaClip/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        OTHER_CODE_SIGN_FLAGS: "--timestamp"
        CODE_SIGN_ENTITLEMENTS: pizzaClip/pizzaClip.entitlements
      configs:
        Release:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
    dependencies:
      - package: GRDB
        product: GRDB
      - package: KeyboardShortcuts
        product: KeyboardShortcuts
      - package: Sparkle
        product: Sparkle
  pizzaClipTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: pizzaClipTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.jekeun.pizzaClipTests
    dependencies:
      - target: pizzaClip
      - package: GRDB
        product: GRDB
schemes:
  pizzaClip:
    build:
      targets:
        pizzaClip: all
        pizzaClipTests: [test]
    test:
      targets:
        - pizzaClipTests
